### ISSUE TITLE
Connect  to DocumentDB using Python

### ISSUE THREAD

**Issue by darshakkakkad** [aws-samples/amazon-documentdb-samples#13]
I am trying to connect to DocumentDB from Python. I looked at some of the examples provided [here](https://github.com/aws-samples/amazon-documentdb-samples/blob/master/samples/connect-and-query/sample_python_documentdb.py). However, my setup is a bit different. I can connect to it from my terminal by creating a ssh tunnel. But, cannot connect from python.

#### Steps taken for connecting from my laptop's terminal. 
- Have with me the `aws_access_key_id ` and `aws_secret_access_key ` which provides me access to the EC2 instance. I do not have username/password.
- Command that starts the tunnel ```AWS_REGION=us-west-2 AWS_PROFILE=<username> ssh -i ~/.ssh/ssm-tunnel-ec2.pem -L 27017:docdb-blah.docdb.amazonaws.com:27017 ec2-user@i-000000000000000 -N -v```.
- Command to launch mongo shell ```mongo --username=<DB_USER> --password=<DB_PASS>```

#### Steps taken for connecting using pymongo library
- Performed [these steps](https://docs.aws.amazon.com/documentdb/latest/developerguide/connect_programmatically.html#connect_programmatically-tls_disabled), but get a Connection Timed out error as soon as i perform an operation using the client.
- Also, tried to create a [SSH Tunnel](https://stackoverflow.com/a/66373424/1133508), but cannot start the tunnel successfully.

Can someone assist. Thanks in advance!

**Comment by tmcallaghan** [comment]
Can you please further explain what is working and what is not? Specifically:
1. If you SSH into your EC2 instance can you connect to DocumentDB via the MongoDB shell?
2. If you SSH into your EC2 instance can you connect to DocumentDB via Python?
3. Are you able to successfully start your SSH tunnel?

**Comment by darshakkakkad** [comment]
@tmcallaghan - Hi thanks for the reply.

1. Yes, works. I can start the tunnel from my laptop and connect to DocumentDB using Mongo shell
2. How can i go about doing this?
3. I can start the tunnel from the terminal, but not from inside python.

**Comment by tmcallaghan** [comment]
@darshakkakkad if you can start the tunnel from your laptop and that tunnel allows you to connect to DocumentDB using the MongoDB shell then I suggest you use this same tunnel for connecting to DocumentDB via Python.

What are you using for your connection string, and DO NOT include username/password here.

client = pymongo.MongoClient('mongodb://<sample-user>:<password>@sample-cluster.node.us-east-1.docdb.amazonaws.com:27017/?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false')

**Comment by darshakkakkad** [comment]
@tmcallaghan What username and password are these - one for connecting to EC2 or the one for DocumentDB itself?

BTW, I am using the very same command you shared. I may be missing something when configuring the MongoClient.

**Comment by tmcallaghan** [comment]
You should be using the username and password for DocumentDB in the pymongo connection string. Also, the fully qualified domain name and port in this connection string should be localhost and the port your ssh tunnel is listening on.

**Comment by darshakkakkad** [comment]
**Command** - 
```
client = MongoClient('mongodb://<DB_USERNAME>:<DB_PASSWORD>@localhost:27017/?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false')
```

**Output** - 
```
Could not reach any servers in [('docdb-blah.us-west-2.docdb.amazonaws.com', 27017)]. Replica set is configured with internal hostnames or IPs?, Timeout: 30s, Topology Description: <TopologyDescription id: XYZ, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('docdb-blah.us-west-2.docdb.amazonaws.com', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('docdb-blah.us-west-2.docdb.amazonaws.com:27017: timed out')>]>

```

**Comment by tmcallaghan** [comment]
@darshakkakkad try using the following, this connects to the cluster endpoint directly (not in replica-set mode).

client = MongoClient('mongodb://<DB_USERNAME>:<DB_PASSWORD>@localhost:27017/?retryWrites=false')

**Comment by darshakkakkad** [comment]
@tmcallaghan That worked successfully! Could you pls explain what difference did that make?

It would be ideal if I could also get the tunneling to work inside my python script. Would you have any ideas how to get it to work? This makes running this on Jenkins possible.

**Comment by darshakkakkad** [comment]
@tmcallaghan I was able to start the tunnel successfully. Thanks for all your help!

For future reference this is my code to start the tunnel and connect to DocumentDB - 
```
        from sshtunnel import SSHTunnelForwarder
        from pymongo import MongoClient

        EC2_URL = "A.B.C.D" # EC2 IP/Hostname
        DB_URI = "docdb-blah.us-west-2.docdb.amazonaws.com" # DocumentDB URI

        # Setup the tunnel connection
        server = SSHTunnelForwarder(
            (EC2_URL),
            ssh_username='ec2-user',
            ssh_pkey='~/.ssh/ssm-tunnel-ec2.pem',  # path of the keyfile here
            remote_bind_address=(DB_URI, 27017),
            local_bind_address=('localhost', 27017)
        )
        # Start the tunnel
        server.start()

        # Setup MongoClient
        client = MongoClient('mongodb://<DB_USERNAME>:<DB_PASSWORD>@localhost:27017/?retryWrites=false')

        # Print any databases. It may be empty if you do not have one created.
        print(client.list_database_names())
  
        # Specify the database name to be created
        db = client["docdbtest"]
        print("Sample DB created")

        # Specify the collection to be created
        col = db["docdbtestcollection"]
        print("Sample collection created")

        # Insert a single document
        col.insert_one({'hello': 'Amazon DocumentDB'})
        print("Inserted one doc")

        # Find the document that was previously written
        x = col.find_one({'hello': 'Amazon DocumentDB'})
        print("Fetched one doc")

        # Print the result to the screen
        print(x)

        # Close the connection
        client.close()
        print("Closing connection")

        # Stop the tunnel
        server.stop()
```

With this, I am closing this issue.
