### ISSUE TITLE
Lambda  fails when WATCHED_COLLECTION_NAME is not provided

### ISSUE THREAD

**Issue by miqayel-manvelyan** [aws-samples/amazon-documentdb-samples#2]
When WATCHED_COLLECTION_NAME is not provided as env variable lambda fails, but I expected it to watch complete DB

**Comment by herbertgoto** [comment]
Can you be more specific about the error? I checked the code and it always evaluates whether that variable is present or not by:
`if "WATCHED_COLLECTION_NAME" in os.environ:`

**Comment by tmcallaghan** [comment]
@miqayel-manvelyan can you please provide more detail on this issue? I'd like to make sure I can reproduce what you are reporting before I create a PR to resolve it.

**Comment by tmcallaghan** [comment]
@miqayel-manvelyan please provide more detail on the issue.

**Comment by tmcallaghan** [comment]
Closing due to lack of response.
